### PR TITLE
Hello ruby

### PR DESCRIPTION
**Pull request by Soumyajit2411**
This is ruby program to output hello world
#Accept the pull request with hackoctoberfest accepted

### CODE REVIEW

**Comment by Soumyajit2411** [comment]
Hey bro change ur level to hacktoberfest

**Comment by Soumyajit2411** [comment]
Hey bro change your  repository level to "hacktoberfest".And if you liked my code accept my request with the level "hacktoberfest-accepted".

**Review by Azhar8080 — CHANGES_REQUESTED** [review]
This code print one line only

**Comment by Azhar8080** [comment]
rb Hello World!

**Comment by Soumyajit2411** [comment]
What?

**Pull request closed without merging**
